### ISSUE TITLE
State of the project.

### ISSUE THREAD

**Issue by vauvenal5** [vauvenal5/yaga#156]
Development got stuck a little over the past months mainly due to time restrictions on my side. However, I have not given up on this project and fully intend to further develop and support it. I hope to find some more time again in the upcoming months for Yaga.

**Comment by daufinsyd** [comment]
Hi @vauvenal5 
That's great to hear 😄 
Thank you for the app btw ! It's certainly the best one ! ❤️

**Comment by arkharim** [comment]
Hi @vauvenal5 
This app was awesome, the best to see photos in nextclous. Nice to know that you still want to develop it further :)

**Comment by devnoname120** [comment]
Hey @vauvenal5 thanks for the app. I can't wait to see development getting picked up again!

**Comment by carling-knock** [comment]
Hi @vauvenal5
wondering about the resent Nextcloud Yaga committed version 0.29.2 that was Updated on 26 Oct 2023 on Play store:
https://play.google.com/store/apps/details?id=com.github.vauvenal5.yaga
can login to Nextcloud, but can't see the remote drive in "Browser view", furthermore the placeholder under the upper left main menu is greyed out, not showing my user icon, name, and Nextcloud Server URL.
Some more glitches along the Settings to place the Path of the local and remote location too, very buggy build, with display shift and doubling of folder names.
Well may I should mention that this is happened on a latest Android 13, Build-No: E940-2849-00_13.0_V05_20230918 may this info coming in handy.

This one seams to be unusable compare to the older Version 0.26.1 (2601) Added on 2021-06-11 available on F-Droid:
https://f-droid.org/en/packages/com.github.vauvenal5.yaga/
That one is working much better, clearly all functions work so far to setup all connections and settings properly, even if some newer features are missing, it's still much more reliable.

Nevertheless, very much hope this project is still coming along since Yaga is a ready useful tool to make use off.

**Comment by vauvenal5** [comment]
Hi.

Okay that is interesting. I testet 0.29.2 on my own Pixel 6 with Android 13 and everything works fine.

Can you pls move this in a separate ticket?

Also a few questions:
- Did you do a clean install or an upgrade?
- Can you send me the log files via email?

Thx for the feedback.

**Comment by vauvenal5** [comment]
I will be closing this since I am again working on the project.

**Comment by carling-knock** [comment]
Ok try to move to a issue and supply more infos once I redo the deinstall of F-Droid Version 0.26.1 (2601), clean out all cash and install again version 0.29.2 from Play store and coming back to you.

**Comment by carling-knock** [comment]
Hey vauvenal5,

please add me to your alpha list for Yaga testing, since I triggered your
interest in continuing to work on the project again.
My Play store email is the same as used in Github, it's
***@***.***

OK one step after another before I redo all the install and deinstall,
clearing the cash and so on my device today, to report back to the issue of
misfunction of my findings.

I'm using a Gigaset GX6 device with the latest Android 13 that was just
released a few days back and set in Dev-mode too.
Not quite sure how to create a Log file, but will make detailed notes of
what I did to pin down the issue.

Thanks
Hanno
