### ISSUE TITLE
Login issue with self signed certificate

### ISSUE THREAD

**Issue by leo-recover** [vauvenal5/yaga#40]
Hi, as title says, I'm trying to connect to my self hosted nextcloud instance, where I'm using a self signed certificate. The log in webview stays blank on the app, as shown below:

![](https://i.imgur.com/ehgDjhL.jpg)
 
May it be because of the self signed certificate?

**Comment by vauvenal5** [comment]
That is entirely possible. To be honest I have not tested the app with a self signed certificate. I will have a look if a quick fix is possible.

**Comment by leo-recover** [comment]
Thanks! By the way, I've switched to Let's Encrypt and I can confirm that with a CA signed certificate the login procedure is fine.

**Comment by vauvenal5** [comment]
It looks to me like the right way to handle this is to import the self signed certificate into the Android trust store instead of enabling the app to handle self signed certs. For the following reasons I will not pursue this issue any further, for the time being:

- It does not look like the Flutter webview supports an easy solution for this and I would need to implement some cert persistence in the app itself.
- WebView based login flow is likely to be replaced in the future, either by the Nextcloud app flow or by a flow using the device browser.
- With Let's Encrypt it is rather easy to have properly signed certs this days.

Some further information to get anyone interested in importing certs into Android started: https://stackoverflow.com/questions/37281958/how-to-trust-self-signed-certificate-on-android

Please feel free to reopen the issue if you want to discuss this further.

**Comment by vauvenal5** [comment]
I am re-opening this since a lot of people seem to use self-signed certs.

**Comment by vauvenal5** [comment]
Self-signed certs are supported in `v0.22.0`. Please note that Yaga will only perform finger print comparison and a check if the subject matches the host.

**Comment by vauvenal5** [comment]
@leo-recover can you confirm this issue as fixed?

**Comment by leo-recover** [comment]
I'm sorry but I can't. As I mentioned above, I've switched to Let's Encrypt, so I'm not using a self signed certificate anymore.

**Comment by vauvenal5** [comment]
Ah sorry. I got my threads mixed up. 

Okay, I am closing this. If anyone has issues with this feel free to re-open.

**Comment by dabru1984** [comment]
Hello, now there is the button "open in browser" only issue is: if i press, nothing happen, am i doing something wrong? @vauvenal5

**Comment by vauvenal5** [comment]
Hi! What version do you have?

**Comment by dabru1984** [comment]
Hello! I got installed the 0.21.2, i have a self signed certificate, i access to the server by an IP address (i got all the rough and special situation i guess, but i am also the only one user of my server and hidden by a VPN, just to explain why anyone would go without a cert) @vauvenal5

**Comment by vauvenal5** [comment]
As mentioned above self signed certs are supported in version `v0.22.0` and higher.

**Comment by dabru1984** [comment]
sorry, but i am unable to log in and the "external browser" function, doesn't work... @vauvenal5

**Comment by vauvenal5** [comment]
Yes that is because you have a self-signed certificate. You have to wait for the update to version **0.22.0**. FDroid is always several days behind. Once you have version 0.22.0 you will be able to use `open in browser` to login.
