### ISSUE TITLE
NextCloud Explorer is empty (LDAP config: username != loginname) 

### ISSUE THREAD

**Issue by politas** [vauvenal5/yaga#53]
My NextCloud server has a dedicated hostname, and my username has no special characters

I'm trying to get logcats, but the method I previously used isn't working.

I've emailed through a "bug report" that seems to be all my phone is letting me collect at this point.

**Comment by vauvenal5** [comment]
Are you already on v0.16.3?

**Comment by politas** [comment]
Yes

**Comment by vauvenal5** [comment]
I have not forgotten this issue. Just had a few other things to finish up.

**Comment by politas** [comment]
I've just emailed a new logcat and screenshot of an error I got trying to login. I then managed to login successfully, but still saw no files. I then tried logging out and logging back in with an app password, and still saw no images/files/folders.

**Comment by vauvenal5** [comment]
I checked you log file. Sadly there is no error message in there. Your screenshot however did confuse me a little bit. First of all, this message appears from time to time, simply retrying usually fixes it. Second, I am trying to understand how far into the process you get, which of the following steps are done by you and how does the app behave?

1. Open app
2. Click `login` in the app drawer
3. Enter URL
4. Click `continue`
5. WebView opens with login mask
6. Enter username+password and login
7. Now the WebView should show you a `Grant access` button, however, due to #35 it could also show you your cloud contents (which of those two happens?)
8. After login, click on `Browse` there should now be an entry with your username and you Nextcloud profile picture
9. Click on that entry
10. Files and folders should load.

![Screenshot_1596215143](https://user-images.githubusercontent.com/1935503/104424633-ecfad080-557f-11eb-9e31-50e62b4c17a3.png)

**Comment by politas** [comment]
Steps 1 through 9 all work, it's just step 10 where it fails down.

After I got that error, I reloaded the app and it acted as though it had accepted the logon with no error,once again taking me all the way to step 9 and then failing to show any contents.

At step 7 I've been getting the grant access button consistently.

All I see is this
![Screenshot_20210113-210554.jpg](https://user-images.githubusercontent.com/2109967/104437733-4516ee80-55e3-11eb-9d43-1ef865561729.jpg)

**Comment by vauvenal5** [comment]
Can you send me a screen shot of your `Browse View`, before selecting your account (step 8)?
Is it possible to get a temporary test user for your cloud?

**Comment by politas** [comment]
These are on my Pixel C tablet:
![Screenshot_20210115-165213.png](https://user-images.githubusercontent.com/2109967/104686960-6ba76780-5752-11eb-9208-e2d2015ba22c.png)
And diving into the NextCloud selection, I get:
![Screenshot_20210115-165222.png](https://user-images.githubusercontent.com/2109967/104687035-84b01880-5752-11eb-9f3b-68020ea34614.png)

**Comment by politas** [comment]
@vauvenal5, I've created an account for you. In fact, I've done it twice, as I had failed to set up the LDAP write settings correctly, so use the second welcome email.

**Comment by politas** [comment]
I've just upgraded to NextCloud 20.0.5, and also my server to Ubuntu 20.4, so I am now running NextCloud under PHP 7.4 - No change in Yaga

**Comment by vauvenal5** [comment]
So I had a look. And I am getting very often a Gateway timeout. In the app as well as in the browser.

![image](https://user-images.githubusercontent.com/1935503/104752563-1de12e00-5757-11eb-83b9-20763908b2f0.png)

**Comment by politas** [comment]
Ah, damn. Looks like I'm getting hit by nextcloud/server#24401. I'll let you know when I've got that under control.

**Comment by politas** [comment]
Should be working again, @vauvenal5

**Comment by vauvenal5** [comment]
Well I have good and bad news... The good, I connected without any issues. The bad, I connected without any issues. Two things I can think of:
1. you have something your file list which I fail to parse correctly
2. its a client side issue

The first one, is simple to check, can you create for yourself a new account and try logging in with it? As for the second, I think you said its an Android 10, anything special about your phone?

**Comment by politas** [comment]
I'm having the same problem with my Pixel C as my phone, so that's unlikely. I just created a test account and got the same result as you - it worked. The test accounts I created for yourself and I are different to the original LDAP accounts, though. My original accounts have random UUIDs that are different to the LDAP username used for login, but are the names of the folders allocated in the Nextcloud storage.
![userlist](https://user-images.githubusercontent.com/2109967/104773590-69342480-57c9-11eb-92b8-dc47a87aea9f.png)
No other apps seem to have a problem with them, I can log in successfully and see relevant files.

**Comment by vauvenal5** [comment]
I will look into it.

**Comment by vauvenal5** [comment]
Okay, I now know what is happening. There is a difference between login name and user name in your case. I now was also able to reproduce it with the test account you provided, by logging in with the email address instead of the user name.

To fix this I will have to open up a ticket with the dart nextcloud library. Will take a bit. 

To be fair the login documentation does mention [this](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html).

**Comment by vauvenal5** [comment]
I opened a PR with the upstream library: https://github.com/Viktoriaschule/dart-nextcloud/pull/19

Once merged I can fix it here.

**Comment by vauvenal5** [comment]
Hi! Should be fixed in `v0.18.2`.

**Comment by vauvenal5** [comment]
Please let me know once you have verified that it works now or directly close the issue.

**Comment by politas** [comment]
Verified working! Thanks for your prompt and excellent response!
