### ISSUE TITLE
Adjust background layer of launcher icon

### ISSUE THREAD

**Issue by stefan-niedermann** [vauvenal5/yaga#87]
Hey there :wave: 

It would be cool if you could use the same background layer (with the gradient) as most of the other Nextcloud apps are using for a more consistent look & feel :slightly_smiling_face: especially for the Play Store icon :wink: 

Here you can find the [SVG](https://raw.githubusercontent.com/nextcloud/talk-android/fb04a7429aeaef4c00e84b8c9f2bb2a7c506be1e/drawable_resources/icon-background.svg) and the [Vector Drawable](https://raw.githubusercontent.com/stefan-niedermann/nextcloud-deck/master/app/src/main/res/drawable/ic_launcher_background.xml)

![Bildschirmfoto am 2021-02-24 um 09 39 52](https://user-images.githubusercontent.com/4741199/108973088-44628500-7684-11eb-813d-b29d8742851c.png)

**Comment by vauvenal5** [comment]
Will do at some point. I am currently a little under water, so development will progress a little bit slower than till now.

**Comment by LukeVader-IV** [comment]
Hey so about a day ago i made a branch with the original icon remade in SVG, as I understand it it should be possible to have the icons be an equivalent of SVG (I now see you also posted the vector drawable) but I'm not too experienced with this and haven't had the time to figure it out yet.
I also made my own spin on the icon as i think the original icon was too generic but I'm not 100% happy with how it turned out.

https://github.com/lucky-day/yaga/tree/svg_icons/assets/icon

I'm also planning to convert all the other icons to SVG if I find the time for it so that there is no need for the current bulk storage solution and have a scalable resolution, If that wouldn't be an inconvenience of course (:

**Comment by vauvenal5** [comment]
Hey! That looks pretty cool. :+1: I myself have not much experience with the graphical part. However, maybe you could use the mountain from the original icon on the second picture of your version. Then you have on one the Nextcloud logo and on the other some more generic suggestion of a picture. Thx for your work in any case :smiley:

**Comment by vauvenal5** [comment]
Another idea that I had in general but did not pursue yet, due to lack of time and graphical skills, is adding the Nextcloud logo above the mountain of the original icon. This would keep the simplicity of the original icon and pair it with the familarity of the Nextcloud logo.

**Comment by LukeVader-IV** [comment]
I like it and I'll try it out, however I'm a little stuck with the other PNG files that are stored in bulk storage due to the file size limit, I tried retrieving the files using git lfs but for some reason I'm having a little trouble with this. I'm probably making an absolutely moronic mistake but could you maybe tell me what exactly i should type in my terminal or send the other PNG files? thanks (:

again, I'm really new to this

**Comment by vauvenal5** [comment]
The stuff that is in Git LFS is for the docs only and is not used in the actual app. However, I decided to separate the docs from the actual code in a separate repo and stop using Git LFS, see #91.

**Comment by LukeVader-IV** [comment]
Ah yeah now I see that screenshots are in fastlane/metadata/android/en-US/images/phoneScreenshots/ but what about docs/assets/images/check.png docs/assets/images/clouds.png and docs/assets/images/phone.png are those simply not used anymore? I feel like a cleanup is very necessary if all the git lfs files are not used anymore

Edit: nvm i realize this is an open issue so those files are still on there, Sorry, getting used to it (:

Also could i simply replace any reference of the original PNG with the new files? because I feel like that wouldn't just work.

one last thing, are the new ones closer to what you wanted? https://github.com/lucky-day/yaga/tree/svg_icons/assets/icon

**Comment by vauvenal5** [comment]
Those look both really nice. I will need to try them out to see how they look on a device. Also I will have to recheck the Android dev guidelines if they satisfy them.

No just replacing will not do the trick since for the Android adaptive icons guideline they have to be split into a foreground and a background. However since the background was simply a color until now it got handled differently. I am using the flutter_launcher_icons library to get the job done and will have to recheck what needs to be done for a gradient.

About the files in `docs/`, they are still used in [here](https://vauvenal5.github.io/yaga/). Those assets are purely for the documentation and not relevant for the app. As mentioned I will be migrating them into a separate repository.

Edit: 
https://developer.android.com/google-play/resources/icon-design-specifications
https://pub.dev/packages/flutter_launcher_icons

**Comment by LukeVader-IV** [comment]
Those links are actually really helpful, thanks, I think I'll go for the original app icon with the nextcloud logo.

Also it will not comply to google's material design specifications but i think a consistent design with the other nextcloud apps is more important

I will probably have time to do this over the weekend

**Comment by stefan-niedermann** [comment]
>  I think I'll go for the original app icon with the nextcloud logo.

Sorry, i didn't read the whole conversation, just read this snippet and wanted to make sure that you are aware of the fact that this is a registered trademark - just to avoid any legal issues :wink:

**Comment by LukeVader-IV** [comment]
ah you're completely right, I hadn't thought of that. However i doubt that this would be much of an issue, I will go and ask for permission beforehand though. Thanks for the reminder :P

**Comment by vauvenal5** [comment]
I think given the discussion in the other thread we will simply stick with the original icon. It is simple and clean.

**Comment by LukeVader-IV** [comment]
hey, I haven't been online due to unfortunate circumstances. However, While I suspect it would fall under fair use, I would not risk it. I won't be able to do any work at least until this weekend but if you wish you could simply take the SVG file and render it to a PNG with a software like inkscape as that's just about the only thing needed for the icon.

PS: i think there is a possibility to use the SVG icon instead of PNG witch would be better but once again, I can't do any research until at least this weekend.

PS 2: if you're willing to wait i could also make a version with the icon used in nextcloud as suggested by jancborchardt and to be perfectly frank i agree that the name could be better

**Comment by LukeVader-IV** [comment]
i made both a version of the original and the icon used by nextcloud
Up to you what you want to use, personally i would do the latter.

**Comment by vauvenal5** [comment]
@LukeVader-IV so I tried it and it is not quiet working out. The inner image is too big. Basically it should be roughly within the bounds of 54x54dp.

I am also considering if it would be a good idea to use Android Vector Drawables instead of SVGs. Would have a similar result as SVGs but I am not sure yet. What are your thoughts on that?

![Screenshot_1615754238](https://user-images.githubusercontent.com/1935503/111083333-5f9b1480-850d-11eb-8c7a-d6462fde5f74.png)

**Comment by vauvenal5** [comment]
After resizing it. However it is not yet ready for publishing. I will have to investigate a little more. Maybe it will be better to stop using this icon generation tool. Set the min supported version to 26 an go with Android Vector Drawables.

![Screenshot_1615756720](https://user-images.githubusercontent.com/1935503/111084492-e999ac00-8512-11eb-8143-01b7cd0e47f6.png)

**Comment by LukeVader-IV** [comment]
yeah I was looking at android vector drawables and i think i might have suggested it at some point however I didn't spend time trying to convert it yet, But I think android studio has a SVG to Vector drawable converter built in So i'll try that soon

also i didn't realise that the foreground was so big as i didn't consider that it would change shape, I'll resize it using the overlay to make sure the size is correct (Stupid mistake)

Edit: anyone know where i can find the design overlay in a normal filetype

Edit 2: should we even deal with PNG files anymore as they're not the best way to do this

**Comment by LukeVader-IV** [comment]
I found some generic online tool that also converts SVG to Vector Drawables, could you maybe try using these files for the icon(I also resized it to a hopefully correct size)

https://github.com/LukeVader-IV/yaga/blob/New-Icons/assets/icon/res-drawable.zip

**Comment by vauvenal5** [comment]
I resized everything and I also managed to use at all points either the SVG or the VectorDrawable. Only disadvantage is that I had to get rid of the icon generator tool. This means in future when changing the SVGs we also have to update the VectorDrawables otherwise everything works.

I have still to do a code cleanup so expect the changes to hit master during the next days.

**Comment by LukeVader-IV** [comment]
Great! If you want i can create a new pull request if you haven't added the files yourself yet.

Happy to hear it worked out (:

**Comment by vauvenal5** [comment]
So funny thing, I got it to work and tested it already with only SVGs and VectorDrawables under the hood. However, two things that I am not sure how to feel about them:
- I had to raise the Android API level from 24 to 26 meaning we are losing ~17% of the users.
- The app is actually ~0.2MB bigger then before. I guess because of the SVG lib I had to add.+

Any thoughts on that?
@stefan-niedermann do we have any user usage statistics for Nextcloud apps?

**Comment by stefan-niedermann** [comment]
> Do we have any user usage statistics for Nextcloud apps?

Just had a look:

| Version | Deck | Notes |
| :-- | --: | --: |
| Android 11 | 32,87 % | 29,92 % |
| Android 10 | 45,81 % | 43,40 % |
| Android 9 | 11,63 % | 13,69 % |
| Android 8.1 | 1,94 % | 2,67 % |
| Android 8.0 | 3,80 % | 4,18 % |
| Android 7.1 | 0,93 % | 1,43 % |
| Android 7.0 | 1,60 % | 2,57 % |
| Android 6.0 | 0,86 % | 1,22 % |
| Android 5.1 | 0,34 % | 0,36 % |
| Android 5.0 | 0,15 % | 0,40 % |
| Android 4.4 | - | 0,10 % |
| Android 4.3 | 0,04 % | 0,02 % |
| Android 4.1 | - | 0,02 % |

Unfortunately i don't have numbers of the official Nextcloud client (we call it "files"), but i guess, they are more conservative there (lower Android versions).
Of course, those numbers are from the Play Store only, i also guess, that the F-Droid users have older Android versions.

All three mentioned apps Have Android 5 (API level `21`) as minimum requirement. We use default images as fallback to the SVG / Vector Drawable versions, but since all mentioned apps are native Android apps, Android Studio greatly supports us with icon generation and the fallbacks for older Android versions.

**Comment by vauvenal5** [comment]
Thx for the information!

I believe I can not go lower then `24` anyway because of Flutter dependencies which I use. So we are talking about roughly 2-5%. I will think about it when I have a moment.

**Comment by vauvenal5** [comment]
Done in `v.0.22.7`. I added support for lower versions.
